spring.application.name=vehicle-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/db_vehicles

#Desativa o Eureka Server para teste
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
