### GATEWAY | Send POST to create client
POST http://localhost:8082/api/clients
Content-Type: application/json

{
  "cpf": "90789830000",
  "nome": "Jorge João Silva",
  "telefone": "11999999999",
  "email": "jorge.joao@teste.com",
  "vehicles": ["ABC1234"]
}